from typing import List
from cascade.analyzers.static.secrets import SecretFinding
from cascade.analyzers.static.sonar import SonarFinding
from cascade.analyzers.static.blast_radius import BlastRadiusResult
from cascade.analyzers.static.regression_risk import RegressionRisk

def render(summary, secrets, sonar, blast, risk, bugs, fixes=None, breakers=None, conflicts=None, policy_violations=None) -> str:
    lines = ["## Cascade Review\n"]

    if summary.get("summary"):
        lines.append(f"**{summary['summary']}**\n")
        lines.append(f"Type: `{summary.get('type', 'UNKNOWN')}` &nbsp;|&nbsp; Regression Risk: `{risk.score}/10 — {risk.level}`\n")

    if secrets:
        lines += ["### ⛔ Secrets Detected\n",
                  "> **Stop. Do not merge. Remove these before pushing.**\n"]
        for s in secrets:
            lines.append(f"- **CRITICAL** `[{s.secret_type}]` — `{s.file}`")
        lines.append("")

    if blast.affected_files:
        lines.append(f"### Blast Radius — `{blast.risk_level}`\n")
        lines.append("| File | Affected symbols |")
        lines.append("|---|---|")
        for path, syms in list(blast.affected_files.items())[:6]:
            lines.append(f"| `{path}` | `{', '.join(syms)}` |")
        lines.append("")

    if sonar:
        lines.append("### SonarQube Simulation\n")
        lines.append("| Severity | Rule | Issue | Est. fix |")
        lines.append("|---|---|---|---|")
        for f in sonar:
            lines.append(f"| {f.severity} | `{f.rule_id}` | {f.description} | {f.debt} |")
        lines.append("")

    if bugs:
        lines.append("### Bugs Found\n")
        for b in bugs:
            lines.append(f"- **{b.get('severity', 'WARNING')}** {b['description']}")
        lines.append("")

    if breakers:
        lines.append("### 🚧 Build Breakers\n")
        lines.append("| Severity | Check | Issue | File |")
        lines.append("|---|---|---|---|")
        for b in breakers:
            lines.append(f"| {b.severity} | `{b.check}` | {b.description} | `{b.file}` |")
        lines.append("")

    if conflicts:
        lines.append("### ⚠ Version Conflicts\n")
        for c in conflicts:
            lines.append(f"- **{c.package}**: {', '.join(f'`{f}: {v}`' for f, v in c.locations.items())}")
        lines.append("")

    if policy_violations:
        lines.append("### Policy Violations\n")
        lines.append("| Severity | Rule | Issue | File |")
        lines.append("|---|---|---|---|")
        for v in policy_violations:
            lines.append(f"| {v.severity} | `{v.rule}` | {v.description} | `{v.file}` |")
        lines.append("")

    if fixes:
        lines.append("### Suggested Fixes\n")
        for fix in fixes:
            lines.append(f"- {fix['description']} *({fix.get('effort', 'small')})*")
        lines.append("")

    lines += ["---",
              "*Generated by [cascade-review](https://github.com/vyshakhgnair/cascade-review) — "
              "free AI code reviewer with SonarQube simulation*"]
    return "\n".join(lines)
